language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t oscarval196/tsapi-dev -f ./api/Dockerfile.dev ./api
  
# heroku plugins:install heroku-container-registry
before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com 
  - docker run -e CI=true oscarval196/tsapi-dev npm run test -- --coverage
  
  
script:
  - docker build -t oscarval196/tsapi ./api
  - docker tag oscarval196/tsapi registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    docker push oscarval196/tsapi;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: main





# Deploying to heroku 

# heroku login
# heroku container:login
# heroku create <YOUR_APP_NAME>
# heroku git:remote -a <YOUR_APP_NAME>
# heroku container:push web <YOUR_APP_NAME>
# heroku container:release web <YOUR_APP_NAME>
# Logout heroku container