sudo: required
language: generic
services:
  - docker
  
before_install:
  - docker build -t oscarval196/tsapi -f Dockerfile.dev ./api

script:
  # -- --coverage exit the process when the test are finished
  - docker run -e CI=true oscarval196/tsapi npm run test -- --coverage



deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"




    sudo: required
language: python
services:
        - docker

before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
        - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com 

script:
        - docker build -t aabhusan/koora:v2 .
        - docker tag aabhusan/koora:v2 registry.heroku.com/$HEROKU_APP/web 
          
deploy:   
        provider: script
        script: 
               docker push aabhusan/koora:v2;
               docker push registry.heroku.com/$HEROKU_APP/web;
               heroku container:release web --app $HEROKU_APP
        on:
          branch: aabhusan


# "oXzgXDWhUhrw47O+3Z1AjLJjtoSEh0gpvkh/ZCyFkEODPbJ0iJQXJirg9ZQuvAW9ElqFSjKUI+TDQHyHIskJhP1d5kGg09HEpvgapVJWsNav6sUQ3i9xm9lgLxk8ifl0kA/eg5YD9x0GStUfR1JIoVJN1RBZt0DBxUzFh78lz7mFbO/NrdpKsBd3/IXeB1+/50+BgnHzdnjjdMzbT3KU3iO1X+pDB6vF31FltUAQOKmuAvhbX5oAjrlo6qrNylH5Vv6Q+cUUvyDlyBjLFLyJg4sZMGu3T2oKsvPsLQUvGB9ZV6o0nHz76yKTWF5LZUg/+u32dKzWI0O8mCX0hxn8polf6cJgGjVCl0gdDlAgT11kz7Bx+rqfSlyNln86uN5Kj1JKQJUFBty+75G+Gr/bqUb2WGHPBLXNXYsnhIcwhcDd9eXgN8duUwfQpx0FG2FGucU2+JJpPqvWB7/OuE2nfsw7gRPrQSRIVOIMMUcrOQQj9VQNytKpdKZoTNlYZQn+xH7XXuZnnqfdIrK2CtvbFCLrKZHhSXVeuAR30sJXBUtTxmp25EYbq6hYLNpfoPHlCULNFZl/hschrPhC6jCunoSr2vH3MvXyC6cb9ATdDLsMCX6cwqnOYZvomOKhMBgRY3gOARkJgDQXiIeaUVT3au4fSOsie/wD5C7LBKQHVnc="